# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cách ly tại nhà HCMCovidSafe
email: hcmcovidsafe.tech4covid.vn
description: >- # this means to ignore newlines until "baseurl:"
  HCMCovidSafe là giải pháp hỗ trợ quản lý và giám sát người đang thực hiện cách ly tại nhà do liên quan dịch bệnh Covid-19. Giải pháp này do Sở TTTT, Sở Y Tế HCM làm chủ sở hữu với sự phối hợp của nhóm Tech4Covid.
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "hcmcovidsafe.tech4covid.vn" # the base hostname & protocol for your site, e.g. https://example.com

# Permalink format (/blog/ is ignored for pages)
permalink: /works/:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# Plugin
plugins:
  - jekyll-postcss

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

social-icons:
  - title: Mail
    url: "mailto:thehien.btk@gmail.com"
    class: mail
  - title: Instagram
    url: https://www.instagram.com/binztk
    class: instagram
  - title: Twitter
    url: https://twitter.com/binztk
    class: twitter
  - title: Youtube
    url: https://www.youtube.com/BinzTK
    class: youtube
  - title: Facebook
    url: https://facebook.com/BinzTK
    class: facebook


contact-lists:
  - quan: "Tân Phú"
    phuong: "mailto:thehien.btk@gmail.com"
    sdt: "mail"
  - quan: "Instagram"
    phuong: "https://www.instagram.com/binztk"
    sdt: "instagram"
  - quan: "Twitter"
    phuong: "https://twitter.com/binztk"
    sdt: "twitter"
  - quan: "Youtube"
    phuong: "https://www.youtube.com/BinzTK"
    sdt: "youtube"
